image: docker:24-cli

services:
  - docker:24-dind

variables:
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
  DOCKER_DRIVER: overlay2
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  LATEST_TAG: $CI_REGISTRY_IMAGE:latest

stages:
  - build
  - test
  - push
  - deploy

# Build Docker image
build:image:
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG -t $LATEST_TAG .
    - docker push $IMAGE_TAG
  only:
    - main
    - develop
    - merge_requests

# Test Docker image
test:image:
  stage: test
  needs: [build:image]
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $IMAGE_TAG
    # Run container and test
    - docker run --rm $IMAGE_TAG npm test
  only:
    - main
    - develop
    - merge_requests

# Security scan with Trivy
security:scan:
  stage: test
  needs: [build:image]
  image: aquasec/trivy:latest
  script:
    - trivy image --exit-code 0 --severity HIGH,CRITICAL $IMAGE_TAG
  allow_failure: true
  only:
    - main
    - develop

# Push latest tag on main branch
push:latest:
  stage: push
  needs: [test:image]
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $IMAGE_TAG
    - docker tag $IMAGE_TAG $LATEST_TAG
    - docker push $LATEST_TAG
  only:
    - main

# Tag and push release versions
push:release:
  stage: push
  needs: [test:image]
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $IMAGE_TAG
    - docker tag $IMAGE_TAG $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  only:
    - tags

# Deploy to staging (Kubernetes example)
deploy:staging:
  stage: deploy
  image: bitnami/kubectl:latest
  needs: [push:latest]
  script:
    - kubectl config use-context $KUBE_CONTEXT
    - kubectl set image deployment/myapp myapp=$IMAGE_TAG -n staging
    - kubectl rollout status deployment/myapp -n staging
  environment:
    name: staging
    url: https://staging.example.com
  only:
    - develop

# Deploy to production (manual approval required)
deploy:production:
  stage: deploy
  image: bitnami/kubectl:latest
  needs: [push:latest]
  script:
    - kubectl config use-context $KUBE_CONTEXT
    - kubectl set image deployment/myapp myapp=$LATEST_TAG -n production
    - kubectl rollout status deployment/myapp -n production
  environment:
    name: production
    url: https://example.com
  only:
    - main
  when: manual

# Cleanup old images (optional, scheduled separately)
cleanup:registry:
  stage: deploy
  script:
    - echo "Cleaning up old registry images..."
    # Add cleanup logic (GitLab API or registry cleanup tool)
  when: manual
  only:
    - main
